[package]
name = "mantis-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22"
getrandom = { workspace = true }
mantis-graph = { workspace = true }
mantis-chain = { workspace = true }
mantis-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tiny_http = { workspace = true }
